name: DCO Check

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for DCO
        id: dco-check
        uses: tisonkun/actions-dco@v1.1
      - name: Comment about DCO status
        uses: actions/github-script@v6
        if: ${{ failure() }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Thank your for your contribution! Please make sure to agree to our DCO by including a  \
              a Signed-off-by message in your commits. You can find the DCO in our [contributing guide](https://github.com/mercedes-benz/disclosure-cli/blob/main/CONTRIBUTING.md). \
              One or more of your commits is missing this message.`
            })